#include "Model.h"

#include <Windows.h>


Model::Model()
{
}

bool Model::LoadModel(const char* pstrFilePath)
{
	try
	{
		// Delete any current model and attempt to load the file into a scene
		Delete();
		Assimp::Importer importer;
		const aiScene* scene = importer.ReadFile(pstrFilePath, aiProcess_Triangulate | aiProcess_FlipUVs | aiProcess_GenNormals);

		// if the file was unable to load for any reason print the error message generated by the model loading library
		if (!scene || scene->mFlags & AI_SCENE_FLAGS_INCOMPLETE || !scene->mRootNode)
		{
			std::cerr << "Failed to load model at " << pstrFilePath << " Error: " << importer.GetErrorString() << std::endl;
			std::string strErr = "Failed to load model file at " + std::string(pstrFilePath);
			MessageBoxA(NULL, strErr.c_str(), NULL, MB_OK | MB_ICONERROR);
			return false;
		}

		// if the model was loaded successfully then begin processing the model data
		ProcessNode(scene->mRootNode, scene);

		// after loading model, free the scene
		importer.FreeScene();
		
		return true;

	}
	catch (const std::exception& e)
	{
		// if any other error occured, show description of error and return
		std::cerr << e.what() << std::endl;
		std::string strErr = "Failed to load model file at " + std::string(pstrFilePath);
		MessageBoxA(NULL, strErr.c_str(), NULL, MB_OK | MB_ICONERROR);
		return false;
	}
	
}

void Model::Draw(MainShader& pShader)
{
	// loops through each mesh in the model and draws it
	for (Mesh& m : mMeshes)
	{
		m.Draw(pShader);
	}
}

void Model::DrawWireframe(LineShader& pShader)
{
	// loops through each mesh in the model and draws it with the line shader to achieve the wireframe
	for(Mesh &m : mMeshes)
	{
		m.DrawWireframe(pShader);
	}
}

void Model::DrawNormals(LineShader& pShader)
{
	// draws the normals of each mesh using the lineshader
	for (Mesh& m : mMeshes)
	{
		m.DrawNormals(pShader);
	}
}

void Model::Delete()
{
	// loops through each mesh and deletes it to deallocate meshes VRAM
	for (Mesh& m : mMeshes)
	{
		m.Delete();
	}

	mMeshes.clear();
}

// this function was taken from https://learnopengl.com/Model-Loading/Model and adapted to this project
void Model::ProcessNode(aiNode* pNode, const aiScene* pScene)
{
	for (int i = 0; i < pNode->mNumMeshes; i++)
	{
		mMeshes.push_back(ProcessMesh(pScene->mMeshes[pNode->mMeshes[i]], pScene));
	}

	for (int i = 0; i < pNode->mNumChildren; i++)
	{
		ProcessNode(pNode->mChildren[i], pScene);
	}
}

Mesh Model::ProcessMesh(aiMesh* pMesh, const aiScene* pScene)
{
	std::vector<Vertex> arrVertices = {};
	std::vector<unsigned int> arrIndices = {};

	// process vertices
	for (int i = 0; i < pMesh->mNumVertices; i++)
	{
		// extract the position data from the current vertex
		Vertex tempVertex;
		tempVertex.pos = glm::vec3(pMesh->mVertices[i].x, pMesh->mVertices[i].y, pMesh->mVertices[i].z);

		// if the mesh contains normals, extract from the vertex
		if (pMesh->mNormals)
			tempVertex.normal = glm::vec3(pMesh->mNormals[i].x, pMesh->mNormals[i].y, pMesh->mNormals[i].z);

		// if the mesh has texture coordinates, extract from the vertex
		if (pMesh->HasTextureCoords(0))
		{
			tempVertex.tex = glm::vec2(pMesh->mTextureCoords[0][i].x, pMesh->mTextureCoords[0][i].y);
		}

		// push the processed vertex to array
		arrVertices.push_back(tempVertex);
	}

	// process indices
	for (int i = 0; i < pMesh->mNumFaces; i++)
	{
		// all mesh faces must have 3 vertices as the main shader can only process triangle
		// so if it encounters a face with a different amount, process the next face
		if (pMesh->mFaces[i].mNumIndices != 3)
		{
			std::cerr << "Something is seriously wrong. num indices " << pMesh->mFaces[i].mNumIndices << std::endl;
			continue;
		} 

		// go through each index in the face and process the 
		for (int j = 0; j < pMesh->mFaces[i].mNumIndices; j++)
		{
			arrIndices.push_back(pMesh->mFaces[i].mIndices[j]);
		}
	}

	aiString strTexturePath;
	strTexturePath = ""; // i literally have to do this

	// process materials
	if (pMesh->mMaterialIndex >= 0)
	{
		std::cerr << "YO THIS HAS A MATERIAL" << std::endl;
		aiMaterial* material = pScene->mMaterials[pMesh->mMaterialIndex];

		// we only want the diffuse textures
		for (int i = 0; i < material->GetTextureCount(aiTextureType_DIFFUSE); i++)
		{
			material->GetTexture(aiTextureType_DIFFUSE, i, &strTexturePath);
		}
	}
	Mesh outMesh;
	
	// check if there is a texture to load or not
	if (!strcmp(strTexturePath.C_Str(), ""))
	{
		outMesh.CreateMesh(arrVertices, arrIndices);
	}
	else
	{
		std::cerr << "Loading Texture..." << std::endl;
		outMesh.CreateMesh(arrVertices, arrIndices, strTexturePath.C_Str());
	}
	std::cerr << std::endl;

	return outMesh;
}

